#!/bin/sh
# Configuration for bspwm: workspaces, program initiations, monitors...
# This script starts automatically when we execute bspwm.

# Remove all existing rules on bspwm reload
bspc rule -r "*"

# Program initializations
# TODO: Maybe move this to .xinitrc and unify it with i3.
sxhkd -c $HOME/.config/sxhkd/sxhkdrc $HOME/.config/sxhkd/sxhkdrc-bspwm &
wallpaper &
compton -f &
mylemonbar &
transmission-gtk -m
dropbox start &
ownclod &
mount $HOME/mat-owncloud &

# Execute screen-layout to set the workpaces
screen-layout únic &

# Window borders and gaps
bspc config border_width 3
bspc config window_gap 20
bspc config top_padding 24	# top_padding equal to lemonbar's height
bspc config bottom_padding 0
bspc config left_padding 0
bspc config right_padding 0
bspc config focus_follows_pointer true
bspc config split_ratio 0.53
bspc config history_aware_focus true
bspc config pointer_modifier mod4
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner

#### BSPWM coloring ####
bspc config normal_border_color	"#2f343f"
bspc config active_border_color	"#2f548f"
bspc config focused_border_color "#2f548f"
bspc config presel_feedback_color "#8000ff"
bspc config urgent_border_color	"#5e3935"
