#!/bin/sh
# Configuration for bspwm: workspaces, program initiations, monitors...
# This script starts automatically when we execute bspwm.

# Load style configurations
[ ! -e $HOME/.local/share/global-style ] && ln -s -T $HOME/.local/share/global-style-blau $HOME/.local/share/global-style

# Remove all existing rules on bspwm reload
bspc rule -r "*"

# Program initializations
# TODO: Maybe move this to .xinitrc and unify it with i3.
pgrep -x sxhkd >/dev/null || sxhkd -c $HOME/.config/sxhkd/sxhkdrc $HOME/.config/sxhkd/sxhkdrc-bspwm &
wallpaper &
pgrep -x compton >/dev/null || compton -f &

# Execute screen-layout to set the workpaces
screen-layout únic

# Window borders and gaps
bspc config border_width 2
bspc config window_gap 10
bspc config top_padding 30	# top_padding equal to lemonbar's height
bspc config bottom_padding 0
bspc config left_padding 0
bspc config right_padding 0
bspc config focus_follows_pointer true
bspc config split_ratio 0.53
#bspc config history_aware_focus true
bspc config pointer_modifier mod4
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner

#### BSPWM coloring ####
. $HOME/.local/share/global-style
bspc config normal_border_color	"$COLOR_BACKGROUND"
bspc config active_border_color	"$COLOR_UNDERLINE"
bspc config focused_border_color "$COLOR_UNDERLINE"
bspc config presel_feedback_color "$COLOR_UNDERLINE_SELECTED"
#bspc config urgent_border_color	"#5e3935"

# Reload the lemonbar
pgrep -x llimabar >/dev/null && pkill llimabar && pkill lemonbar
llimabar &

# "Heavy" applications autostart
pgrep transmission >/dev/null || transmission-gtk -m &
pgrep -x dropbox >/dev/null || dropbox start &
pgrep -x owncloud >/dev/null || owncloud &
mountpoint -q $HOME/mat-owncloud || mount $HOME/mat-owncloud &

[ -e "$LLIMA_FIFO" ] && bspc subscribe report >"$LLIMA_FIFO" &
